
title: Sam's Zone
email: samharris23@live.com
author: Sam Harris

url: "https://samharris.tech/"
baseurl: "" # Keep Empty

description: > # description of the site (multiple lines allowed)
  My Small Corner of the Internet

favicon: "icon.ico" # name+extension of favicon (which must be put on the root folder)
theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # "light", "dark", "auto"
  back_home_text: "Return" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
